import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F8FAFC' },
  container: { flex: 1, paddingHorizontal: 16, paddingTop: 12 },
  header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  headerText: { flex: 1, paddingRight: 10 },
  screenName: { color: '#64748B', fontSize: 12, fontWeight: '900' },
  appName: { color: '#0F172A', fontSize: 24, fontWeight: '900', marginTop: 2 },
  dateText: { color: '#153E75', fontSize: 14, fontWeight: '900', marginTop: 2 },
  subcopy: { color: '#64748B', fontSize: 13, fontWeight: '800', marginTop: 4 },
  updatedNotice: {
    alignSelf: 'flex-start',
    backgroundColor: '#DCFCE7',
    borderRadius: 8,
    color: '#166534',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 6,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  headerActions: { flexDirection: 'row', gap: 7 },
  iconButton: {
    alignItems: 'center',
    backgroundColor: '#EAF2FF',
    borderColor: '#B8D4FF',
    borderRadius: 8,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  iconButtonDark: { alignItems: 'center', backgroundColor: '#153E75', borderRadius: 8, height: 40, justifyContent: 'center', width: 40 },
  content: { paddingBottom: 172 },
  priorityRow: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 9,
    padding: 12,
  },
  priorityHeader: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 6 },
  priorityBadge: {
    backgroundColor: '#153E75',
    borderRadius: 999,
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  rowName: { color: '#0F172A', fontSize: 15, fontWeight: '900' },
  actionType: { color: '#64748B', fontSize: 12, fontWeight: '900' },
  shortReason: { color: '#334155', lineHeight: 20 },
  todoLine: { color: '#153E75', fontWeight: '900', lineHeight: 20, marginTop: 4 },
  rowButtons: { flexDirection: 'row', gap: 8, marginTop: 10 },
  rowMeta: { color: '#64748B', lineHeight: 19, marginTop: 2 },
  searchBox: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D7DEE8',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  searchInput: { color: '#0F172A', flex: 1, fontSize: 15 },
  filterTitle: { color: '#334155', fontSize: 13, fontWeight: '900', marginBottom: 8, marginTop: 14 },
  filterRow: { flexGrow: 0 },
  summary: { marginBottom: 8, marginTop: 16 },
  addPersonButton: {
    alignItems: 'center',
    backgroundColor: '#153E75',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginBottom: 12,
    minHeight: 48,
  },
  addPersonButtonText: { color: '#FFFFFF', fontWeight: '900' },
  summaryText: { color: '#64748B', fontWeight: '900' },
  empty: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 8, borderWidth: 1, marginTop: 8, padding: 20 },
  emptyTitle: { color: '#0F172A', fontSize: 16, fontWeight: '900' },
  emptyText: { color: '#64748B', lineHeight: 20, marginTop: 8 },
  emptyButton: { alignItems: 'center', backgroundColor: '#153E75', borderRadius: 8, justifyContent: 'center', marginTop: 14, minHeight: 46 },
  emptyButtonText: { color: '#FFFFFF', fontWeight: '900' },
  questionBlock: { marginBottom: 12 },
  questionText: { color: '#153E75', fontWeight: '900', lineHeight: 20, marginBottom: 6 },
  afterContextCard: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  afterContextTitle: { color: '#0F172A', fontSize: 17, fontWeight: '900' },
  afterContextMeta: { color: '#475569', fontWeight: '800', marginTop: 4 },
  afterContextFocus: { color: '#153E75', fontWeight: '900', lineHeight: 20, marginTop: 7 },
  aiExtractHintCard: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  aiExtractTitle: { color: '#0F172A', fontSize: 14, fontWeight: '900' },
  aiExtractText: { color: '#475569', lineHeight: 20, marginTop: 6 },
  inlineActions: { flexDirection: 'row', gap: 10, marginBottom: 10 },
  primaryCta: {
    alignItems: 'center',
    backgroundColor: '#153E75',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
  },
  primaryCtaText: { color: '#FFFFFF', fontWeight: '900', textAlign: 'center' },
  secondaryCta: {
    alignItems: 'center',
    backgroundColor: '#EAF2FF',
    borderColor: '#B8D4FF',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
  },
  secondaryCtaText: { color: '#153E75', fontWeight: '900', textAlign: 'center' },
  paneHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  paneHeaderText: { flex: 1, paddingRight: 10 },
  paneTitle: { color: '#0F172A', fontSize: 22, fontWeight: '900' },
  paneSubcopy: { color: '#64748B', fontWeight: '800', lineHeight: 20, marginTop: 3 },
  paneHeaderActions: { flexDirection: 'row', gap: 8 },
  smallOutlineButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 12,
  },
  smallOutlineText: { color: '#0F172A', fontSize: 12, fontWeight: '900' },
  personSelectCard: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 9,
    padding: 12,
  },
  personSelectCardActive: {
    backgroundColor: '#FFFFFF',
    borderColor: '#0F172A',
  },
  personSelectTop: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  personSelectName: { color: '#0F172A', fontSize: 16, fontWeight: '900' },
  selectedMark: {
    backgroundColor: '#0F172A',
    borderRadius: 999,
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  personSelectMeta: { color: '#475569', fontWeight: '800', marginTop: 5 },
  personSelectTags: { color: '#153E75', fontSize: 12, fontWeight: '900', marginTop: 7 },
  personSelectAction: { color: '#334155', lineHeight: 20, marginTop: 5 },
  selectedPersonSummary: {
    backgroundColor: '#0F172A',
    borderRadius: 8,
    marginTop: 10,
    padding: 12,
  },
  selectedSummaryLabel: { color: '#CBD5E1', fontSize: 11, fontWeight: '900' },
  selectedSummaryName: { color: '#FFFFFF', fontSize: 17, fontWeight: '900', marginTop: 3 },
  selectedSummaryMeta: { color: '#E2E8F0', fontWeight: '800', marginTop: 4 },
  selectedSummaryAction: { color: '#FFFFFF', lineHeight: 20, marginTop: 7 },
  changePersonButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginTop: 10,
    minHeight: 46,
  },
  changePersonText: { color: '#0F172A', fontWeight: '900' },
  resultHint: { color: '#64748B', fontSize: 12, fontWeight: '900', marginTop: 12, marginBottom: 7 },
  sheetBackdrop: {
    backgroundColor: 'rgba(15, 23, 42, 0.38)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  personPickerSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '82%',
    padding: 16,
  },
  sheetHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sheetTitle: { color: '#0F172A', fontSize: 20, fontWeight: '900' },
  sheetSubcopy: { color: '#64748B', fontWeight: '800', lineHeight: 19, marginTop: 3 },
  sheetCloseButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 12,
  },
  sheetCloseText: { color: '#0F172A', fontSize: 12, fontWeight: '900' },
  personPickerList: { maxHeight: 430 },
  emptyPickerState: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
  },
  guidanceText: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    color: '#334155',
    fontWeight: '800',
    lineHeight: 20,
    marginTop: 10,
    padding: 10,
  },
  referenceSummaryCard: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  referenceSummaryTitle: { color: '#0F172A', fontSize: 15, fontWeight: '900' },
  referenceSummaryText: { color: '#334155', lineHeight: 20, marginTop: 5 },
  referenceSummaryCaution: { color: '#B45309', fontWeight: '900', lineHeight: 20, marginTop: 6 },
  toggleRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    marginBottom: 10,
    marginTop: 10,
    minHeight: 42,
  },
  toggleText: { color: '#0F172A', fontWeight: '900' },
  referenceGrid: {
    columnGap: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  navSummaryCard: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  questionPreview: {
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  questionPreviewTitle: { color: '#0F172A', fontWeight: '900', marginBottom: 6 },
  questionPreviewText: { color: '#153E75', fontWeight: '900', lineHeight: 21, marginTop: 4 },
  fullPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#153E75',
    borderRadius: 8,
    justifyContent: 'center',
    marginBottom: 12,
    minHeight: 52,
  },
  fullPrimaryText: { color: '#FFFFFF', fontSize: 15, fontWeight: '900' },
  primaryActionStack: { gap: 10, marginTop: 4 },
  primaryCtaWide: {
    alignItems: 'center',
    backgroundColor: '#153E75',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 50,
  },
  moreActionPanel: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 10,
    padding: 10,
  },
  successNotice: {
    alignSelf: 'flex-start',
    backgroundColor: '#DCFCE7',
    borderRadius: 8,
    color: '#166534',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  endSummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 12,
  },
  endSummaryCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minWidth: '46%',
    padding: 12,
  },
  endSummaryWarning: {
    backgroundColor: '#FFF7ED',
    borderColor: '#FED7AA',
  },
  endSummaryDanger: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
  },
  endSummaryValue: {
    color: '#0F172A',
    fontSize: 22,
    fontWeight: '900',
  },
  endSummaryLabel: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 4,
  },
  unprocessedCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FBBF24',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  unprocessedHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  unprocessedType: {
    backgroundColor: '#FEF3C7',
    borderRadius: 999,
    color: '#92400E',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  unprocessedTarget: {
    color: '#0F172A',
    fontWeight: '900',
  },
  cardUpdateRow: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  endStatusPill: {
    backgroundColor: '#EAF2FF',
    borderRadius: 999,
    color: '#153E75',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  tomorrowRow: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    padding: 12,
  },
  bottomNav: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    bottom: 82,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 16,
    paddingHorizontal: 4,
    paddingVertical: 7,
    position: 'absolute',
    right: 16,
  },
  navItem: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: 52,
  },
  navIconButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    width: 36,
  },
  navIconButtonActive: { backgroundColor: '#F1F5F9' },
  navLabel: {
    color: '#94A3B8',
    fontSize: 10,
    fontWeight: '900',
    marginTop: 3,
  },
  navLabelActive: { color: '#0F172A' },
  floatingActions: { bottom: 18, flexDirection: 'row', gap: 10, left: 16, position: 'absolute', right: 16 },
  floatingButton: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 52,
  },
  coachButton: { backgroundColor: '#EAF2FF', borderColor: '#B8D4FF', borderWidth: 1 },
  coachButtonText: { color: '#153E75', fontWeight: '900' },
});
